apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresdb:5432/postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  POSTGRESHOST: "postgresdb"
  KAFKA_NOOFRETRIES: "1"
  KAFKA_HOST: "broker"
  ORDER_TOPIC: "kafka-listen-messages"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  ELASTIC_HOST: "elasticsearch"
  ELASTIC_PORT: "9200"
  KAFKA_PRODUCER_BOOTSTRAP_SERVERS_HOST: "broker"
  KAFKA_PRODUCER_BOOTSTRAP_SERVERS_PORT: "9092"